### PR TITLE
Add AppVeyor config

### PR DESCRIPTION
**Pull request by DanRStevens**
Add AppVeyor config for automated continuous integration builds.

----

@ldicker83: Can you look into adding the NAS2D project to the OP2-Landlord solution file? We also need the OP2-Landlord project to depend on the NAS2D project.

### CODE REVIEW

**Comment by ldicker83** [comment]
It's a little different than I'm used to doing it but it seems to make more sense since NAS2D isn't published via NuGet or vcpkg. All the dependencies are there anyway so it should build just fine.

Should I have it build a library binary and then link against it (e.g., OP2-Landlord depends on NAS2D building) or should I just have the project simply build the code directly into the OP2-Landlord binary skipping the interim step? I see benefits to both approaches, I'm just undecided which way I should go.

**Comment by DanRStevens** [comment]
They should remain as separate projects. The NAS2D project should should already be configured to build a static library. The OP2-Landlord project should just add a dependency on that project. It might require some project configuration for include folders or library folders, though I suspect Visual Studio might handle at least the library stuff for you automatically.

This all assumes the Git submodule setup makes the NAS2D project available at a known subfolder.

If you want to look at other similar setups, the [OP2MapImager](https://github.com/OutpostUniverse/OP2MapImager) and [OP2Archive](https://github.com/OutpostUniverse/OP2Archive) projects both depend on the OP2Utility static library project, which is setup as a Git submodule. In both cases, the solution file contains two projects, with the main executable project dependent on the static library project. A fresh checkout will automatically build both projects from source.

**Comment by DanRStevens** [comment]
Well that didn't work out so great. @Brett208, we could probably use a bit of help with this.

**Comment by Brett208** [comment]
It builds okay on my local machine after removing the .lib calls. I looked at the path @DanRStevens added to the Visual Studio project files and they seem to make sense.

I noticed we are using the Visual Studio 2019 preview. It might be worth switching to the Visual Studio 2017 toolset to see if that helps. Otherwise, I'm not sure what else to try. 

I tried removing the cache on appveyor just in case that mattered, but it didn't help.

-Brett

**Comment by DanRStevens** [comment]
Oh, because this branch is using an older version of NAS2D, from before the VS2019 project file was added.

**Comment by DanRStevens** [comment]
Ok, progress. The new error message is:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(447,5): error MSB4018: The "NativeCodeAnalysis" task failed unexpectedly. [C:\projects\op2-landlord\nas2d-core\proj\vs2019\NAS2D.vcxproj]
```

----

@Brett208, thank you for the help with this.

In regards to the `AdditionalDependencies` update, I noticed there are still other similar settings for other project configurations. I guess we should edit those too at some point.

I think some of this may be complicated by the "Release Gold" configuration in NAS2D. I'm not sure how configurations map to each other between projects.

**Comment by DanRStevens** [comment]
Thanks for the update.

Curiously, only the `Release|Win32` configuration fails now. I checked the project file settings. The two release configurations have identical settings. I'm not too sure how to approach this error. I did notice the many lines of errors are different though, with one line containing perhaps a big clue:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(447,5): error MSB4018: The "NativeCodeAnalysis" task failed unexpectedly. [C:\projects\op2-landlord\nas2d-core\proj\vs2019\NAS2D.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(447,5): error MSB4018: Microsoft.VisualStudio.CodeAnalysis.AnalysisResults.AnalysisResultException: CA0001 : An unknown error occurred while running Code Analysis. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\Rule Sets\NativeRecommendedRules.ruleset'. [C:\projects\op2-landlord\nas2d-core\proj\vs2019\NAS2D.vcxproj]
```

There are references to both Visual Studio 16, and Visual Studio 14, with the later showing a path not found error. It sounds like it's trying to run a tool for an older version of Visual Studio.

I found an article that may have a bit of detail:
[MSBuild error MSB4018 with VS2013 while doing analyze](https://social.msdn.microsoft.com/Forums/vstudio/en-US/cc0dfb93-9f18-40bd-9c6f-377808bcd34e/msbuild-error-msb4018-with-vs2013-while-doing-analyze?forum=msbuild)

**Comment by Brett208** [comment]
Looks like you got this to build.

**Comment by DanRStevens** [comment]
Aha, finally! Thank you everyone for your help!

**Pull request merged**
